name: Weekly Sync from Develop to Stage

on:
  workflow_dispatch:

jobs:
  createPR:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: develop

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update stage with develop
          branch: stage
          delete-branch: true
          title: Weekly update from develop
          body: |
            This is an automated pull request to update stage with the latest code from develop.
          draft: false
          reviewers: cyz@gmail.com,xyz@gmail.com
